### PR TITLE
expand account details for organization

### PR DESCRIPTION
**Pull request by RobBrazier**
*Issue #, if available:*
#387

*Description of changes:*
Expands account details to ensure that accounts defined without organization details do not remove org id configuration from servicecatalog-puppet-policies stacks

I'm still working on getting some tests written as it doesn't seem like there are any for expand yet (there is for explode though), but wanted to get it out there in case there was someone else working on it as well

Is it expected for customers to be using this without an organization? if so, I might need to add a check for that (on my personal account I get `AWSOrganizationsNotInUseException` when calling describe_account as expected)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by eamonnfaherty** [comment]
Thanks for the PR. I am hoping to release a new version tomorrow/today. It's quite a big refactor and a new feature. I will look at this once I have the merge complete and will hopefully include it in the release of its ready.

**Comment by eamonnfaherty** [comment]
At the moment it is not assumed that a customer will be using Organizations however, the code you have written will only be executed if a customer has enabled Organizations support.  It should be fine.

**Comment by eamonnfaherty** [comment]
Let me know if you need any help with the unit testing.  It would be good to at least not have a drop in coverage when adding this.  I have recently added 7% coverage and have added some e2e automated testing.  I would like to try to continue this if possible.  

You can run the tests by running make unit-tests for a one off run otherwise you can run make unit-test-watcher to watch the files and run the tests whenever there is a change.

**Comment by RobBrazier** [comment]
I couldn't seem to find any other cases where a boto3 client is passed into the method, so made a full mock, not sure if that's the way you'd normally do that - we normally use botocore stubber to do this, although as expand_ou is calling `list_children_nested` I'm assuming the client is a better-boto one, so that wouldn't work :)

**Pull request merged**
